name: Deploy Website
on:
  push:
    branches: [ main ]
  # workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.139.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget --progress=bar:force:noscroll -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb  
          DEBIAN_FRONTEND=noninteractive sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - uses: actions/checkout@v4
        name: Checkout main branch
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive
      
      - name: Build Website with Hugo
        run: hugo

      - uses: actions/checkout@v4
        name: Checkout gh-pages repo
        with:
          ref: gh-pages
          fetch-depth: 0
          path: emerald

      - name: Copy main/public To gh-pages/emerald
        working-directory: emerald
        run: |
          rm -rf *
          cp -rf ../public/* .
      
      - name: Commit Website Updates
        working-directory: emerald
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy website updates with GitHub Actions: ${GITHUB_SHA}"
          git push origin gh-pages